* Minimizing model complexity
* Penalizing the loss function 
* Reducing model overfitting (adding more bias to reduce model variance)

* L1 Reg - LASSO - small coefficients are treated as 0 , abs value
* L2 Reg - Ridge - adds a penallty to the square of the magnitude, coefficient are shrunk by the same factors but not removed like LASSO
* L3 Reg - Elastic Net - Combines them both with an additional alpha parameter for the ration between them

These reg methods introudce additional hyperparameters like alpha and beta - multiplier to the penalties

# Feature Scaling


New data must always be scaled to be appropriate for the training model, coeff become easier to compare but harder to relate to original coeff
<br>
Feature Scaling has no downsides and it imporves performance, some algorithms require it 

2 features scaling: 
* Standartization - Rescale data with mean of 0 and sd of 1 
* Normalization - Rescale values from 0 to 1

.fit() method call calculates the necessary stats, like Xmin and Xmax <br>
.transform() will perform the process of standartization and normalization

<b> We only fit to training data </b> <br> If we fit in the test we perform what is known as data leaking. We expose the model to the test set

Feature Scaling Process:
* Perform a train test split
* Fit to trainnig feature data
* Transaform training feature data
* Tranform test feature data

# Do not scale the label <br>
Does not impact the perfomance model

# Cross Validation
<br> Cross Validation is a more advanced set of methods for splitting data into training and testing sets. Is there anyway to train and test in all the data. <br>
We perform the test multiple times, in this case K-times to be exact

K-fold cross-validation - usually K is 10 where each test is 10% of the data <br>
The max number of K is the number of rows

# We cannot tune after the fianl result

![](https://cdn.discordapp.com/attachments/750394985068626120/1014163567127298068/unknown.png)

We get a final Test value and we cannot tune any more hyper parameters after this

# Regularization For Linear Regression

In [62]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt 
import pandas as pd

In [63]:
df = pd.read_csv('notebook/08-Linear-Regression-Models/Advertising.csv')
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [64]:
X = df.drop('sales', axis=1)
y = df['sales']

In [65]:
from sklearn.preprocessing import PolynomialFeatures

polynomial_converter = PolynomialFeatures(degree=3, include_bias=False)

In [66]:
poly_features = polynomial_converter.fit_transform(X)
poly_features.shape

(200, 19)

In [67]:
from sklearn.model_selection import train_test_split

In [68]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size= 0.3, random_state= 101)

In [69]:
X_train.shape

(140, 19)

In [70]:
from sklearn.preprocessing import StandardScaler

In [71]:
scaler = StandardScaler()

In [72]:
scaler.fit(X_train) # only fit the scaler to the training set

StandardScaler()

In [73]:
X_train = scaler.transform(X_train)

In [74]:
X_test = scaler.transform(X_test)

In [75]:
X_train[0] # values are small now

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

# Ridge Regression <br>
Is a regularization method for linear Regresssion <br>
We are trying to split the data into train and test without overfitting  <br>
Overfitting means that we have a high variance, we have to trade bias for variance <br>
We introduce a bit of bias to remove a lot of variance - This will reduce overfitting - Adding bias will pick up less noise and lower the variance <br>
This will punish a large slope by increasing the bias and making the slope less steep which will yield better results while testing for future points

# Implementing L2 Regression / Ridge Regression

# NOTE : Skleanr refers to lambda as alpha within the class call, to keep the framework constant

In [76]:
from sklearn.linear_model import Ridge 
help(Ridge)
# alpha is the penalty factor
# w

Help on class Ridge in module sklearn.linear_model._ridge:

class Ridge(sklearn.base.MultiOutputMixin, sklearn.base.RegressorMixin, _BaseRidge)
 |  Ridge(alpha=1.0, *, fit_intercept=True, normalize='deprecated', copy_X=True, max_iter=None, tol=0.001, solver='auto', positive=False, random_state=None)
 |  
 |  Linear least squares with l2 regularization.
 |  
 |  Minimizes the objective function::
 |  
 |  ||y - Xw||^2_2 + alpha * ||w||^2_2
 |  
 |  This model solves a regression model where the loss function is
 |  the linear least squares function and regularization is given by
 |  the l2-norm. Also known as Ridge Regression or Tikhonov regularization.
 |  This estimator has built-in support for multi-variate regression
 |  (i.e., when y is a 2d-array of shape (n_samples, n_targets)).
 |  
 |  Read more in the :ref:`User Guide <ridge_regression>`.
 |  
 |  Parameters
 |  ----------
 |  alpha : {float, ndarray of shape (n_targets,)}, default=1.0
 |      Constant that multiplies the L2 t

In [77]:
ridge_model = Ridge(alpha=10)

In [78]:
ridge_model.fit(X_train, y_train) # just like linear regresssion we fit the data

Ridge(alpha=10)

In [79]:
test_predictions = ridge_model.predict(X_test)
test_predictions

array([13.7469803 , 19.17764   , 11.8623393 , 16.25574551,  8.92891155,
        8.04595366, 20.13320851, 16.94847676, 10.29219174, 19.78365691,
       10.31758361, 13.44077317, 12.24228062, 23.23864236, 19.12656362,
        9.748809  , 12.84361521,  9.14248129,  8.82504966, 21.46989971,
        8.25222201, 18.8110776 , 28.39227333, 25.06911066,  9.11912241,
       11.8071711 , 20.85199462,  9.31962495, 12.25122303,  9.07811198,
        9.25275556, 19.87154568, 10.55955497,  7.86818084, 17.67220132,
        9.31442423, 10.1539168 ,  9.47802944,  8.63337302, 10.76209179,
       11.63848891, 10.38883411, 10.90270005,  8.40019284, 11.35336224,
       10.3514086 ,  8.00082147, 15.27139854, 12.94761469, 22.49762978,
       10.80165407, 13.01337743, 14.82204895, 11.37354043, 11.69628953,
        7.20576885, 25.53512232, 10.41926545, 17.38798022, 15.10158819])

In [80]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [81]:
MAE = mean_absolute_error(y_test, test_predictions)
MAE

0.5774404204714163

In [82]:
RMSE = mean_squared_error(y_test, test_predictions)
np.sqrt(RMSE)

0.894638646131965

<b> We dont know if alpha = 10 is the best choice so we have to use cross validation to test a variety of alphas/lambdas </b>

In [83]:
# We import a diff ridge regression model
from sklearn.linear_model import RidgeCV # Ridge Cross Validation
# this will report the back the best alpha performance

In [84]:
ridgeCV_model = RidgeCV(alphas=(0.1, 1, 10)) # alphas is a tuple with multiple alphas
# by default it performs leave one out cross validation - it means k cross validations, done by the cv param


In [85]:
ridgeCV_model.fit(X_train, y_train) # this becomes a training and a validation set to test the performance
# X_train is the whole data set minus the folds

RidgeCV(alphas=(0.1, 1, 10))

In [86]:
# performance
ridgeCV_model.alpha_ # returns the best performing alpha 

0.1

<b> To find the best performing alpha we assing a scoring metric

In [87]:
from sklearn.metrics import SCORERS # to import scoring metrics

In [88]:
SCORERS.keys() # this is a dictionary object
# These are all the errors 


dict_keys(['explained_variance', 'r2', 'max_error', 'matthews_corrcoef', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_s

# These Errors are transformed to mean that higher is better

neg_mean_absolute_error in this case is negative since a higher value (closer to 0) means a smaller error which yields better performanc

In [89]:
ridgeCV_model = RidgeCV(alphas=(0.1, 1, 10), scoring='neg_mean_absolute_error') # now it will score for this param
ridgeCV_model

RidgeCV(alphas=(0.1, 1, 10), scoring='neg_mean_absolute_error')

In [90]:
ridgeCV_model.fit(X_train, y_train)
ridgeCV_model.alpha_

0.1

# Check Performance for this model

In [91]:
test_predictions = ridgeCV_model.predict(X_test)
test_predictions

array([14.25006161, 19.10205204, 12.44776087, 17.07029103,  7.93609517,
        7.10314552, 19.94990664, 17.24524365, 10.33548736, 19.85951926,
        9.37933062, 13.9569529 , 11.85445773, 23.29303451, 19.30247423,
        9.42431717, 12.42484839,  9.21704461,  8.70229329, 21.42382243,
        7.14698141, 19.35684761, 27.33199316, 24.44887898,  9.23720121,
       11.46268721, 20.47427126,  9.4597969 , 12.55070677,  8.39250566,
        8.7928193 , 19.92435249, 10.8069225 ,  7.10760344, 18.16473242,
        9.30970124, 10.54163577,  9.71377387,  7.31109512, 10.76826686,
       12.32939318, 10.34155545, 11.39134453,  7.74592784, 11.73219215,
       10.60945023,  5.74446924, 15.33163484, 13.01377062, 22.65350817,
       10.59700761, 12.94758932, 14.71822795, 12.01718014, 11.35600126,
        5.47860188, 24.96469385,  9.42600079, 17.27904849, 15.59419989])

<b> Both of the errors have fallen

In [92]:
MAE = mean_absolute_error(y_test, test_predictions)
MAE

0.427377488434534

In [93]:
RMSE = mean_squared_error(y_test, test_predictions)
np.sqrt(RMSE)

0.6180719926938822

In [94]:
ridgeCV_model.coef_
# none of this coef are close to 0 but that will change with lasso regression

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

# LASSO Regression <br>
L1 Regularization, unlike Ridge Regg it considers the absolute value of the coef and not the square value, this allows some coef to be 0 when the tunning param alpha/lambda is small enough <br>
These will let us not interpret some features makeing the model more efficient and faster <br>
This model will check multiple alphas/lambdas by default

** LASSO - least absolute shrinkage and selection operator

In [95]:
from sklearn.linear_model import LassoCV 
# we import LassoCV to test for multiple alpha valeus

There are different types of Lasso algorithms you can check in the documentation

In [96]:
# eps - ration of min alpha value with the max alpha value
# n_alphas - like linspace for alphas

lassoCV_model = LassoCV(eps = 0.001, n_alphas=100, cv=5, max_iter=1000) # these are the default values
# eps gets smaller - more values 
# n_alphas higher - more values
# cv - the number of k folds - by default it uses a 5 fold cross validation

In [97]:
lassoCV_model.fit(X_train, y_train)
# there is a convergance warning meaning that the stoccastic search didnt converge
# to fix this error increase max_iter=
# another way is to lower the eps search to like 0.1 so the ratio is smaller andd we arent searching as wide

/home/zaimi/Desktop/python/venv/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.870e+00, tolerance: 3.684e-01
  model = cd_fast.enet_coordinate_descent(


LassoCV(cv=5)

In [98]:
lassoCV_model = LassoCV(eps = 0.001, n_alphas=100, cv=5, max_iter=1000000) # these are the default values
lassoCV_model.fit(X_train, y_train) # this fit just fine

LassoCV(cv=5, max_iter=1000000)

In [99]:
lassoCV_model = LassoCV(eps = 0.1, n_alphas=100, cv=5, max_iter=1000) # changed esp here
lassoCV_model.fit(X_train, y_train) # this fit just fine

LassoCV(cv=5, eps=0.1)

In [100]:
lassoCV_model.alpha_ # this is the best alpha

0.4943070909225832

In [101]:
test_predictions = lassoCV_model.predict(X_test)
test_predictions

array([13.45338009, 19.25419883, 11.92693647, 15.65984482,  9.59275546,
        8.91555193, 20.13945651, 16.8940403 , 10.30392219, 19.35585759,
       10.53851739, 13.52523076, 11.84291254, 21.97446984, 18.50473737,
       10.18416558, 12.51310389,  9.62098689,  9.58916887, 20.90872394,
        9.01385339, 18.173473  , 27.16694718, 24.24589466,  9.88609246,
       11.41696271, 21.15799353,  9.85860773, 12.19996303,  9.4393254 ,
        9.57055425, 19.39654459, 10.68194027,  8.72638276, 17.22100511,
        9.65240517, 10.54721814,  9.97920093,  8.9632026 , 10.659277  ,
       11.98376175, 10.3246849 , 11.10752122,  9.02040466, 11.57917154,
       10.78030361,  8.57798137, 15.15282195, 12.72136342, 21.35302125,
       10.86548461, 12.78550905, 14.91137805, 11.70074134, 11.30228394,
        8.43176178, 24.92405026, 10.66203455, 17.58679446, 14.93460903])

In [102]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [103]:
MAE = mean_absolute_error(y_test, test_predictions)
MAE

0.6541723161252867

In [104]:
RMSE = mean_squared_error(y_test, test_predictions)
np.sqrt(RMSE)

1.1308001022762548

# LASSO ISNT PERFORMING AS GOOD AS THE RIDGE REGRESSION

The benefit is that LASSO is only considering only 2 coef everything else isnt being considered, the performance is quite impressive.

In [105]:
lassoCV_model.coef_
# Most likely these are the Radio and TV features

array([1.002651  , 0.        , 0.        , 0.        , 3.79745279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

# Testing for a better LASSO MODEL

In [106]:
lassoCV_model = LassoCV(eps=0.001, n_alphas=100, max_iter=1000000)

In [107]:
lassoCV_model.fit(X_train, y_train)

LassoCV(max_iter=1000000)

In [108]:
test_predictions = lassoCV_model.predict(X_test)

In [109]:
MAE = mean_absolute_error(y_test, test_predictions)
MAE

0.4335034618590078

In [110]:
RMSE = mean_squared_error(y_test, test_predictions)
np.sqrt(RMSE)

0.6063140748984043

In [111]:
lassoCV_model.coef_ # naturally the model will consider more coefficient
# since we searched for more alpha it will search for a more conmplex model

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])

This is a slightly better version of ridge regression since we have a lot of 0 coeff in here

# Elastic Net regression combines Lasso and Ridge regression together

Elasticc Net needs CV to get good results

In [112]:
from sklearn.linear_model import ElasticNetCV

In [113]:
# l1_ration - this means the lassor ration
# closer to 0 means Ridge
# closer to 1 means Lasso 
# Reccomanded that we approach lasso more, the default value is 0.5
elasticModel = ElasticNetCV(l1_ratio=[.1, .5, .7, .9, .95, .99, 1], eps=0.001, n_alphas=100, max_iter=1000000)

In [114]:
elasticModel.fit(X_train, y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [116]:
elasticModel.l1_ratio # returns all the ratios

[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1]

In [118]:
elasticModel.l1_ratio_ # returns the best ratio, disregards ridge completely, we will get the same results as the normal model

1.0

In [119]:
test_predictions = elasticModel.predict(X_test)
test_predictions

array([14.16203485, 19.2942685 , 12.34178429, 16.97745571,  8.02340978,
        6.95799942, 20.11875833, 17.32880647, 10.43139937, 19.96174466,
        9.56959473, 13.94205676, 11.90851817, 23.35138146, 19.56656277,
        9.27838151, 12.30485359,  9.30152997,  8.56733436, 21.51633564,
        7.06650884, 19.3377222 , 27.28027149, 24.52239173,  9.17172464,
       11.60918126, 20.73841405,  9.29953525, 12.56948515,  8.40051066,
        8.56984613, 20.03587647, 10.83439653,  6.79505173, 18.18820331,
        9.48107219, 10.41803957,  9.70785725,  7.22932328, 10.85467692,
       12.85491418, 10.51648453, 11.26905127,  7.41516944, 11.54705407,
       10.42233031,  6.02782344, 15.36338733, 13.18723611, 22.67619584,
       10.4721906 , 13.01165791, 14.56684361, 11.90062303, 11.47303307,
        5.59404766, 25.06115365,  9.69468957, 17.44771723, 15.60375637])

In [120]:
MAE = mean_absolute_error(y_test, test_predictions)
MAE

0.4335034618590078

In [121]:
RMSE = mean_squared_error(y_test, test_predictions)
np.sqrt(RMSE)

0.6063140748984043